#!/usr/bin/env python3
"""
Generate web_assets.generated.h from style.css and main.js.
Assets are embedded as C++ raw string literals in the binary.
"""
import argparse
import sys


DELIM = "embed"  # Raw string delimiter; must not appear as )embed" in CSS/JS


def main():
    ap = argparse.ArgumentParser(description="Embed style.css and main.js into a C++ header")
    ap.add_argument("--css", required=True, help="Path to style.css")
    ap.add_argument("--js", required=True, help="Path to main.js")
    ap.add_argument("-o", "--output", required=True, help="Output header path")
    args = ap.parse_args()

    try:
        with open(args.css, "r", encoding="utf-8") as f:
            css = f.read()
    except OSError as e:
        sys.stderr.write(f"embed_assets: cannot read {args.css}: {e}\n")
        sys.exit(1)

    try:
        with open(args.js, "r", encoding="utf-8") as f:
            js = f.read()
    except OSError as e:
        sys.stderr.write(f"embed_assets: cannot read {args.js}: {e}\n")
        sys.exit(1)

    if f"){DELIM}\"" in css or f"){DELIM}\"" in js:
        sys.stderr.write(f"embed_assets: content must not contain ){DELIM}\" (would break raw string)\n")
        sys.exit(1)

    out = f'''/** Generated by embed_assets.py from style.css and main.js. Do not edit. */
#pragma once

namespace {{

const char STYLE_CSS[] = R"{DELIM}(
{css}){DELIM}";

const char MAIN_JS[] = R"{DELIM}(
{js}){DELIM}";

}} // namespace
'''

    try:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
    except OSError as e:
        sys.stderr.write(f"embed_assets: cannot write {args.output}: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
