#!/usr/bin/env python3
"""
Generate rules.generated.h from rule files in embed/rules/.
Rules are embedded as C++ raw string literals in the binary.
Accepts .mdc and .md files.
"""
import argparse
import os
import sys


DELIM = "embed"  # Raw string delimiter; must not appear as )embed" in content


def sanitize_name(path):
    """Convert file path to a valid C++ identifier.
    Example: 'solid-principles.mdc' -> 'SOLID_PRINCIPLES_MDC'
    """
    name = os.path.basename(path)
    # Replace dots and dashes with underscores
    name = name.replace(".", "_").replace("-", "_")
    return name.upper()


def main():
    ap = argparse.ArgumentParser(description="Embed rule files into a C++ header")
    ap.add_argument("--rules-dir", required=True, help="Path to embed/rules/ directory")
    ap.add_argument("-o", "--output", required=True, help="Output header path")
    args = ap.parse_args()

    if not os.path.isdir(args.rules_dir):
        sys.stderr.write(f"embed_rules: {args.rules_dir} is not a directory\n")
        sys.exit(1)

    rule_files = {}
    extensions = (".mdc", ".md")
    for filename in sorted(os.listdir(args.rules_dir)):
        if not any(filename.endswith(ext) for ext in extensions):
            continue
        filepath = os.path.join(args.rules_dir, filename)
        if not os.path.isfile(filepath):
            continue

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            var_name = sanitize_name(filename)
            rule_files[var_name] = {
                "filename": filename,
                "content": content
            }
        except OSError as e:
            sys.stderr.write(f"embed_rules: cannot read {filepath}: {e}\n")
            sys.exit(1)

    if not rule_files:
        sys.stderr.write(f"embed_rules: no .mdc or .md files found in {args.rules_dir}\n")
        sys.exit(1)

    # Check for delimiter conflicts
    for var_name, file_data in rule_files.items():
        if f"){DELIM}\"" in file_data["content"]:
            sys.stderr.write(f"embed_rules: file {file_data['filename']} must not contain ){DELIM}\" (would break raw string)\n")
            sys.exit(1)

    # Generate header content
    declarations = []
    filename_map = []

    for var_name, file_data in sorted(rule_files.items()):
        filename = file_data["filename"]
        content = file_data["content"]
        declarations.append(f'const char {var_name}_CONTENT[] = R"{DELIM}(\n{content}){DELIM}";')
        declarations.append(f'const char {var_name}_FILENAME[] = "{filename}";')
        filename_map.append(f'    {{ {var_name}_FILENAME, {var_name}_CONTENT }},')

    out = f'''/** Generated by embed_rules.py from embed/rules/*.mdc. Do not edit. */
#pragma once

#include <cstddef>

struct RuleFile {{
    const char* filename;
    const char* content;
}};

{chr(10).join(declarations)}

inline const RuleFile RULE_FILES[] = {{
{chr(10).join(filename_map)}
}};

inline constexpr std::size_t NUM_RULE_FILES = {len(rule_files)};
'''

    try:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
    except OSError as e:
        sys.stderr.write(f"embed_rules: cannot write {args.output}: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
