#!/usr/bin/env python3
"""
Generate agents.generated.h from markdown files in docs/roles_agents/.
Agents are embedded as C++ raw string literals in the binary.
"""
import argparse
import os
import sys


DELIM = "embed"  # Raw string delimiter; must not appear as )embed" in markdown


def sanitize_name(path):
    """Convert file path to a valid C++ identifier.
    Example: 'taskman-developer.md' -> 'TASKMAN_DEVELOPER_MD'
    """
    name = os.path.basename(path)
    # Replace dots and dashes with underscores
    name = name.replace(".", "_").replace("-", "_")
    return name.upper()


def main():
    ap = argparse.ArgumentParser(description="Embed agent markdown files into a C++ header")
    ap.add_argument("--agents-dir", required=True, help="Path to docs/roles_agents/ directory")
    ap.add_argument("-o", "--output", required=True, help="Output header path")
    args = ap.parse_args()

    if not os.path.isdir(args.agents_dir):
        sys.stderr.write(f"embed_agents: {args.agents_dir} is not a directory\n")
        sys.exit(1)

    agent_files = {}
    # Read all .md files in the agents directory
    for filename in sorted(os.listdir(args.agents_dir)):
        if not filename.endswith(".md"):
            continue
        filepath = os.path.join(args.agents_dir, filename)
        if not os.path.isfile(filepath):
            continue
        
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            var_name = sanitize_name(filename)
            agent_files[var_name] = {
                "filename": filename,
                "content": content
            }
        except OSError as e:
            sys.stderr.write(f"embed_agents: cannot read {filepath}: {e}\n")
            sys.exit(1)

    if not agent_files:
        sys.stderr.write(f"embed_agents: no .md files found in {args.agents_dir}\n")
        sys.exit(1)

    # Check for delimiter conflicts
    for var_name, file_data in agent_files.items():
        if f"){DELIM}\"" in file_data["content"]:
            sys.stderr.write(f"embed_agents: file {file_data['filename']} must not contain ){DELIM}\" (would break raw string)\n")
            sys.exit(1)

    # Generate header content
    declarations = []
    filename_map = []
    
    for var_name, file_data in sorted(agent_files.items()):
        filename = file_data["filename"]
        content = file_data["content"]
        declarations.append(f'const char {var_name}_CONTENT[] = R"{DELIM}(\n{content}){DELIM}";')
        declarations.append(f'const char {var_name}_FILENAME[] = "{filename}";')
        filename_map.append(f'    {{ {var_name}_FILENAME, {var_name}_CONTENT }},')

    out = f'''/** Generated by embed_agents.py from docs/roles_agents/*.md. Do not edit. */
#pragma once

#include <cstddef>

struct AgentFile {{
    const char* filename;
    const char* content;
}};

{chr(10).join(declarations)}

inline const AgentFile AGENT_FILES[] = {{
{chr(10).join(filename_map)}
}};

inline constexpr std::size_t NUM_AGENT_FILES = {len(agent_files)};
'''

    try:
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
    except OSError as e:
        sys.stderr.write(f"embed_agents: cannot write {args.output}: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
